project/views/frontend.py
from flask import Blueprint, request

from project import app

frontend = Blueprint(
    "frontend", __name__, static_folder="../static/frontend", static_url_path="/"
)


@frontend.route("/")
def index(path=None):  # pragma: no cover
    return frontend.send_static_file("index.html")


@frontend.errorhandler(404)
def not_found(e):  # pragma: no cover
    if request.path.startswith("/api"):
        return "", 404

    return frontend.send_static_file("index.html")


app.register_blueprint(frontend)

project/templates/_macros.html
{% macro render_field_with_errors(field) %}
    {% set is_collapsible = kwargs['is_collapsible'] if 'is_collapsible' in kwargs else False %}
    {% if is_collapsible %}
    <div class="mb-3" id="{{ field.id }}-show-container"{% if field.data %} style="display: none;"{% endif %}>
      <a href="#" class="show-link" data-container="{{ field.id }}-container" data-show-container="{{ field.id }}-show-container"><i class="fa fa-plus"></i> {{ field.label.text }}</a>
    </div>
    <div id="{{ field.id }}-container"{% if not field.data %} style="display: none;"{% endif %}>
    {% endif %}

      {% set is_required = kwargs['is_required'] if 'is_required' in kwargs else field.flags.required %}
      {% set label_text = field.label.text + ' *' if is_required else field.label.text %}
      <div class="form-group {% if field.errors %} has-error{% endif -%} {% if 'formrow' in kwargs %} row{% endif -%}">
        {% if 'label_hidden' in kwargs or ('ri' in kwargs and kwargs['ri'] == 'checkbox') %}
        {% else %}
          {% set label_class = "col-sm-2 col-form-label" if 'formrow' in kwargs else "mb-0" %}
          {{ field.label(text=label_text, class=label_class) }}
        {% endif %}

        {% if 'formrow' in kwargs %}
        <div class="col-sm-10">
        {% endif %}

        {% if field.description %}
          <div class="form-text mt-0 text-muted w-100">
            {{ field.description }}
          </div>
        {% endif %}

        <div class="input-group">
          {% set field_class = kwargs['class'] if 'class' in kwargs else '' %}
          {% set field_class = field_class + ' form-control' %}
          {% if field.errors %}
            {% set field_class = field_class + ' is-invalid' %}
          {% endif %}

          {% if 'ri' in kwargs and kwargs['ri'] == 'multicheckbox' %}
            <fieldset class="form-group">
              {% for choice in field %}
                  <div class="form-check">
                      {{ choice(class="form-check-input") }}
                      {{ choice.label(class="form-check-label") }}
                  </div>
              {% endfor %}
            </fieldset>
          {% elif 'ri' in kwargs and kwargs['ri'] == 'multicheckbox-inline' %}
            <fieldset class="form-group my-auto">
              {% for choice in field %}
                  <div class="form-check form-check-inline">
                      {{ choice(class="form-check-input") }}
                      {{ choice.label(class="form-check-label") }}
                  </div>
              {% endfor %}
            </fieldset>
          {% elif 'ri' in kwargs and kwargs['ri'] == 'checkbox' %}
            <div class="form-check">
                {{ field(class="form-check-input") }}
                {{ field.label(class="form-check-label") }}
            </div>
          {% elif 'ri' in kwargs and kwargs['ri'] == 'switch' %}
            <div class="custom-control custom-switch">
              {{ field(class="custom-control-input") }}
              <label class="custom-control-label" for="{{ field.id }}"></label>
            </div>
          {% elif 'ri' in kwargs and kwargs['ri'] == 'radio-buttons' %}
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
              {% for choice in field %}
                  {% set color = kwargs['colors'][loop.index0] if 'colors' in kwargs else 'secondary' %}
                  <label class="btn btn-outline-{{ color }}">
                    <input type="radio" id="{{ choice.id }}" name="{{ field.id }}" value="{{ choice.id[-1] }}" {% if choice.checked %}checked {% endif %}> {{ choice.label.text }}
                  </label>
              {% endfor %}
            </div>
          {% else %}
            {% if 'class' in kwargs %}
              {% set _dummy=kwargs.pop('class') %}
            {% endif %}
            {{ field(class=field_class, **kwargs)|safe }}
          {% endif %}

          {% if 'ri' in kwargs %}
            {% if kwargs['ri'] == 'rrule' %}
              <script type="text/javascript">
                $( function() {
                  $("textarea[name=recurrence_rule]").recurrenceinput({lang:'de', startField: "start",  ajaxURL: "{{ url_for('event_rrule') }}", firstDay: 1});
                });
              </script>
            {% endif %}
          {% endif %}
        </div>

        {% if field.errors %}
        <div class="invalid-feedback d-block">
            {% for error in field.errors %}
            <div>{{ error }}</div>
            {% endfor %}
        </div>
        {% endif %}

        {% if 'formrow' in kwargs %}
      </div>
        {% endif %}
      </div>

    {% if is_collapsible %}
      <div class="mb-3" id="{{ field.id }}-hide-container">
        <a href="#" class="hide-link" data-container="{{ field.id }}-container" data-show-container="{{ field.id }}-show-container"><i class="fa fa-minus"></i> {{ field.label.text }}</a>
      </div>
    </div>
    {% endif %}
{% endmacro %}

{% macro render_field(field) %}
  <p>{{ field(class="btn btn-primary", **kwargs)|safe }}</p>
{% endmacro %}

{% macro render_field_errors(field) %}
  <p>
    {% if field and field.errors %}
      <ul>
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  </p>
{% endmacro %}

project/templates/layout.html
<!doctype html>
<html lang="de">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='site.css')}}" />

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.js" integrity="sha256-HwXB0HPJCXhungCtZoScc1a53ngQOXua64nb0cI6PHY=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js" integrity="sha256-AdQN98MVZs44Eq2yTwtoKufhnU+uZ7v2kXnD5vqzZVo=" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>

    <script>
      moment.locale('de')
    </script>

    {% block header %}
    {% endblock %}
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('frontend.index') }}">
        <img src="{{ url_for('static', filename='apple-touch-icon.png')}}" width="30" height="30" class="d-inline-block align-top rounded" alt="Logo">
        Goslar Service App
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/news">News</a>
          </div>
          {% if current_user.is_authenticated %}
            <div class="navbar-nav navbar-right">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarUserDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ current_user.email }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarUserDropdown">
                  <a class="dropdown-item" href="{{ url_for('security.logout') }}">{{ _('Logout') }}</a>
                </div>
              </li>
            </div>
          {% endif %}
      </div>
  </nav>

    <div class="body-content">
        {% block content %}
        {% endblock %}
        <footer>
            <p class="text-center">Mit <i class="fa fa-heart" style="color: red"></i> in <strong>Goslar</strong> entwickelt.</p>
            <p class="text-center small"><a href="/impressum">Impressum</a> | <a href="/impressum">Kontakt</a> | <a href="/datenschutz">Datenschutz</a></p>
        </footer>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>